// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: graph.proto

package graph

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphService_CreateGraph_FullMethodName         = "/varyd.api.v1.GraphService/CreateGraph"
	GraphService_DropGraph_FullMethodName           = "/varyd.api.v1.GraphService/DropGraph"
	GraphService_DescribeGraph_FullMethodName       = "/varyd.api.v1.GraphService/DescribeGraph"
	GraphService_CreateNode_FullMethodName          = "/varyd.api.v1.GraphService/CreateNode"
	GraphService_GetNode_FullMethodName             = "/varyd.api.v1.GraphService/GetNode"
	GraphService_UpdateNode_FullMethodName          = "/varyd.api.v1.GraphService/UpdateNode"
	GraphService_DeleteNode_FullMethodName          = "/varyd.api.v1.GraphService/DeleteNode"
	GraphService_ListNodes_FullMethodName           = "/varyd.api.v1.GraphService/ListNodes"
	GraphService_CreateEdge_FullMethodName          = "/varyd.api.v1.GraphService/CreateEdge"
	GraphService_GetEdge_FullMethodName             = "/varyd.api.v1.GraphService/GetEdge"
	GraphService_UpdateEdge_FullMethodName          = "/varyd.api.v1.GraphService/UpdateEdge"
	GraphService_DeleteEdge_FullMethodName          = "/varyd.api.v1.GraphService/DeleteEdge"
	GraphService_ListEdges_FullMethodName           = "/varyd.api.v1.GraphService/ListEdges"
	GraphService_Traverse_FullMethodName            = "/varyd.api.v1.GraphService/Traverse"
	GraphService_ShortestPath_FullMethodName        = "/varyd.api.v1.GraphService/ShortestPath"
	GraphService_AllPaths_FullMethodName            = "/varyd.api.v1.GraphService/AllPaths"
	GraphService_Centrality_FullMethodName          = "/varyd.api.v1.GraphService/Centrality"
	GraphService_CommunityDetection_FullMethodName  = "/varyd.api.v1.GraphService/CommunityDetection"
	GraphService_PageRank_FullMethodName            = "/varyd.api.v1.GraphService/PageRank"
	GraphService_ConnectedComponents_FullMethodName = "/varyd.api.v1.GraphService/ConnectedComponents"
	GraphService_CycleDetection_FullMethodName      = "/varyd.api.v1.GraphService/CycleDetection"
	GraphService_MatchPattern_FullMethodName        = "/varyd.api.v1.GraphService/MatchPattern"
	GraphService_Subgraph_FullMethodName            = "/varyd.api.v1.GraphService/Subgraph"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphServiceClient interface {
	// Graph management
	CreateGraph(ctx context.Context, in *CreateGraphRequest, opts ...grpc.CallOption) (*CreateGraphResponse, error)
	DropGraph(ctx context.Context, in *DropGraphRequest, opts ...grpc.CallOption) (*DropGraphResponse, error)
	DescribeGraph(ctx context.Context, in *DescribeGraphRequest, opts ...grpc.CallOption) (*DescribeGraphResponse, error)
	// Node operations
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Edge operations
	CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*CreateEdgeResponse, error)
	GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*GetEdgeResponse, error)
	UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...grpc.CallOption) (*UpdateEdgeResponse, error)
	DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error)
	ListEdges(ctx context.Context, in *ListEdgesRequest, opts ...grpc.CallOption) (*ListEdgesResponse, error)
	// Traversal operations
	Traverse(ctx context.Context, in *TraverseRequest, opts ...grpc.CallOption) (*TraverseResponse, error)
	ShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error)
	AllPaths(ctx context.Context, in *AllPathsRequest, opts ...grpc.CallOption) (*AllPathsResponse, error)
	// Graph algorithms
	Centrality(ctx context.Context, in *CentralityRequest, opts ...grpc.CallOption) (*CentralityResponse, error)
	CommunityDetection(ctx context.Context, in *CommunityDetectionRequest, opts ...grpc.CallOption) (*CommunityDetectionResponse, error)
	PageRank(ctx context.Context, in *PageRankRequest, opts ...grpc.CallOption) (*PageRankResponse, error)
	ConnectedComponents(ctx context.Context, in *ConnectedComponentsRequest, opts ...grpc.CallOption) (*ConnectedComponentsResponse, error)
	CycleDetection(ctx context.Context, in *CycleDetectionRequest, opts ...grpc.CallOption) (*CycleDetectionResponse, error)
	// Pattern matching
	MatchPattern(ctx context.Context, in *MatchPatternRequest, opts ...grpc.CallOption) (*MatchPatternResponse, error)
	Subgraph(ctx context.Context, in *SubgraphRequest, opts ...grpc.CallOption) (*SubgraphResponse, error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) CreateGraph(ctx context.Context, in *CreateGraphRequest, opts ...grpc.CallOption) (*CreateGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGraphResponse)
	err := c.cc.Invoke(ctx, GraphService_CreateGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) DropGraph(ctx context.Context, in *DropGraphRequest, opts ...grpc.CallOption) (*DropGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropGraphResponse)
	err := c.cc.Invoke(ctx, GraphService_DropGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) DescribeGraph(ctx context.Context, in *DescribeGraphRequest, opts ...grpc.CallOption) (*DescribeGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeGraphResponse)
	err := c.cc.Invoke(ctx, GraphService_DescribeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, GraphService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, GraphService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeResponse)
	err := c.cc.Invoke(ctx, GraphService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodeResponse)
	err := c.cc.Invoke(ctx, GraphService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, GraphService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*CreateEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEdgeResponse)
	err := c.cc.Invoke(ctx, GraphService_CreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*GetEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeResponse)
	err := c.cc.Invoke(ctx, GraphService_GetEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...grpc.CallOption) (*UpdateEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEdgeResponse)
	err := c.cc.Invoke(ctx, GraphService_UpdateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEdgeResponse)
	err := c.cc.Invoke(ctx, GraphService_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) ListEdges(ctx context.Context, in *ListEdgesRequest, opts ...grpc.CallOption) (*ListEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEdgesResponse)
	err := c.cc.Invoke(ctx, GraphService_ListEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) Traverse(ctx context.Context, in *TraverseRequest, opts ...grpc.CallOption) (*TraverseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraverseResponse)
	err := c.cc.Invoke(ctx, GraphService_Traverse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) ShortestPath(ctx context.Context, in *ShortestPathRequest, opts ...grpc.CallOption) (*ShortestPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortestPathResponse)
	err := c.cc.Invoke(ctx, GraphService_ShortestPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) AllPaths(ctx context.Context, in *AllPathsRequest, opts ...grpc.CallOption) (*AllPathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllPathsResponse)
	err := c.cc.Invoke(ctx, GraphService_AllPaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) Centrality(ctx context.Context, in *CentralityRequest, opts ...grpc.CallOption) (*CentralityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CentralityResponse)
	err := c.cc.Invoke(ctx, GraphService_Centrality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) CommunityDetection(ctx context.Context, in *CommunityDetectionRequest, opts ...grpc.CallOption) (*CommunityDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommunityDetectionResponse)
	err := c.cc.Invoke(ctx, GraphService_CommunityDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) PageRank(ctx context.Context, in *PageRankRequest, opts ...grpc.CallOption) (*PageRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageRankResponse)
	err := c.cc.Invoke(ctx, GraphService_PageRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) ConnectedComponents(ctx context.Context, in *ConnectedComponentsRequest, opts ...grpc.CallOption) (*ConnectedComponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectedComponentsResponse)
	err := c.cc.Invoke(ctx, GraphService_ConnectedComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) CycleDetection(ctx context.Context, in *CycleDetectionRequest, opts ...grpc.CallOption) (*CycleDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CycleDetectionResponse)
	err := c.cc.Invoke(ctx, GraphService_CycleDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) MatchPattern(ctx context.Context, in *MatchPatternRequest, opts ...grpc.CallOption) (*MatchPatternResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchPatternResponse)
	err := c.cc.Invoke(ctx, GraphService_MatchPattern_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) Subgraph(ctx context.Context, in *SubgraphRequest, opts ...grpc.CallOption) (*SubgraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubgraphResponse)
	err := c.cc.Invoke(ctx, GraphService_Subgraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility.
type GraphServiceServer interface {
	// Graph management
	CreateGraph(context.Context, *CreateGraphRequest) (*CreateGraphResponse, error)
	DropGraph(context.Context, *DropGraphRequest) (*DropGraphResponse, error)
	DescribeGraph(context.Context, *DescribeGraphRequest) (*DescribeGraphResponse, error)
	// Node operations
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Edge operations
	CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeResponse, error)
	GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error)
	UpdateEdge(context.Context, *UpdateEdgeRequest) (*UpdateEdgeResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error)
	ListEdges(context.Context, *ListEdgesRequest) (*ListEdgesResponse, error)
	// Traversal operations
	Traverse(context.Context, *TraverseRequest) (*TraverseResponse, error)
	ShortestPath(context.Context, *ShortestPathRequest) (*ShortestPathResponse, error)
	AllPaths(context.Context, *AllPathsRequest) (*AllPathsResponse, error)
	// Graph algorithms
	Centrality(context.Context, *CentralityRequest) (*CentralityResponse, error)
	CommunityDetection(context.Context, *CommunityDetectionRequest) (*CommunityDetectionResponse, error)
	PageRank(context.Context, *PageRankRequest) (*PageRankResponse, error)
	ConnectedComponents(context.Context, *ConnectedComponentsRequest) (*ConnectedComponentsResponse, error)
	CycleDetection(context.Context, *CycleDetectionRequest) (*CycleDetectionResponse, error)
	// Pattern matching
	MatchPattern(context.Context, *MatchPatternRequest) (*MatchPatternResponse, error)
	Subgraph(context.Context, *SubgraphRequest) (*SubgraphResponse, error)
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServiceServer struct{}

func (UnimplementedGraphServiceServer) CreateGraph(context.Context, *CreateGraphRequest) (*CreateGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGraph not implemented")
}
func (UnimplementedGraphServiceServer) DropGraph(context.Context, *DropGraphRequest) (*DropGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropGraph not implemented")
}
func (UnimplementedGraphServiceServer) DescribeGraph(context.Context, *DescribeGraphRequest) (*DescribeGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeGraph not implemented")
}
func (UnimplementedGraphServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedGraphServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedGraphServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedGraphServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedGraphServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedGraphServiceServer) CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEdge not implemented")
}
func (UnimplementedGraphServiceServer) GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdge not implemented")
}
func (UnimplementedGraphServiceServer) UpdateEdge(context.Context, *UpdateEdgeRequest) (*UpdateEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEdge not implemented")
}
func (UnimplementedGraphServiceServer) DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedGraphServiceServer) ListEdges(context.Context, *ListEdgesRequest) (*ListEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEdges not implemented")
}
func (UnimplementedGraphServiceServer) Traverse(context.Context, *TraverseRequest) (*TraverseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Traverse not implemented")
}
func (UnimplementedGraphServiceServer) ShortestPath(context.Context, *ShortestPathRequest) (*ShortestPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShortestPath not implemented")
}
func (UnimplementedGraphServiceServer) AllPaths(context.Context, *AllPathsRequest) (*AllPathsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllPaths not implemented")
}
func (UnimplementedGraphServiceServer) Centrality(context.Context, *CentralityRequest) (*CentralityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Centrality not implemented")
}
func (UnimplementedGraphServiceServer) CommunityDetection(context.Context, *CommunityDetectionRequest) (*CommunityDetectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommunityDetection not implemented")
}
func (UnimplementedGraphServiceServer) PageRank(context.Context, *PageRankRequest) (*PageRankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PageRank not implemented")
}
func (UnimplementedGraphServiceServer) ConnectedComponents(context.Context, *ConnectedComponentsRequest) (*ConnectedComponentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectedComponents not implemented")
}
func (UnimplementedGraphServiceServer) CycleDetection(context.Context, *CycleDetectionRequest) (*CycleDetectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CycleDetection not implemented")
}
func (UnimplementedGraphServiceServer) MatchPattern(context.Context, *MatchPatternRequest) (*MatchPatternResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchPattern not implemented")
}
func (UnimplementedGraphServiceServer) Subgraph(context.Context, *SubgraphRequest) (*SubgraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subgraph not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}
func (UnimplementedGraphServiceServer) testEmbeddedByValue()                      {}

// UnsafeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServiceServer will
// result in compilation errors.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	// If the following call panics, it indicates UnimplementedGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_CreateGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CreateGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CreateGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CreateGraph(ctx, req.(*CreateGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_DropGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).DropGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_DropGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).DropGraph(ctx, req.(*DropGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_DescribeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).DescribeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_DescribeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).DescribeGraph(ctx, req.(*DescribeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_CreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CreateEdge(ctx, req.(*CreateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetEdge(ctx, req.(*GetEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_UpdateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).UpdateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_UpdateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).UpdateEdge(ctx, req.(*UpdateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).DeleteEdge(ctx, req.(*DeleteEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_ListEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).ListEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_ListEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).ListEdges(ctx, req.(*ListEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_Traverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).Traverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_Traverse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).Traverse(ctx, req.(*TraverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_ShortestPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortestPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).ShortestPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_ShortestPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).ShortestPath(ctx, req.(*ShortestPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_AllPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).AllPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_AllPaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).AllPaths(ctx, req.(*AllPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_Centrality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CentralityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).Centrality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_Centrality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).Centrality(ctx, req.(*CentralityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_CommunityDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommunityDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CommunityDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CommunityDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CommunityDetection(ctx, req.(*CommunityDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_PageRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).PageRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_PageRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).PageRank(ctx, req.(*PageRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_ConnectedComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectedComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).ConnectedComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_ConnectedComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).ConnectedComponents(ctx, req.(*ConnectedComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_CycleDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CycleDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).CycleDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_CycleDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).CycleDetection(ctx, req.(*CycleDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_MatchPattern_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchPatternRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).MatchPattern(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_MatchPattern_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).MatchPattern(ctx, req.(*MatchPatternRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_Subgraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubgraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).Subgraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_Subgraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).Subgraph(ctx, req.(*SubgraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphService_ServiceDesc is the grpc.ServiceDesc for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "varyd.api.v1.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGraph",
			Handler:    _GraphService_CreateGraph_Handler,
		},
		{
			MethodName: "DropGraph",
			Handler:    _GraphService_DropGraph_Handler,
		},
		{
			MethodName: "DescribeGraph",
			Handler:    _GraphService_DescribeGraph_Handler,
		},
		{
			MethodName: "CreateNode",
			Handler:    _GraphService_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _GraphService_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _GraphService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _GraphService_DeleteNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _GraphService_ListNodes_Handler,
		},
		{
			MethodName: "CreateEdge",
			Handler:    _GraphService_CreateEdge_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _GraphService_GetEdge_Handler,
		},
		{
			MethodName: "UpdateEdge",
			Handler:    _GraphService_UpdateEdge_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _GraphService_DeleteEdge_Handler,
		},
		{
			MethodName: "ListEdges",
			Handler:    _GraphService_ListEdges_Handler,
		},
		{
			MethodName: "Traverse",
			Handler:    _GraphService_Traverse_Handler,
		},
		{
			MethodName: "ShortestPath",
			Handler:    _GraphService_ShortestPath_Handler,
		},
		{
			MethodName: "AllPaths",
			Handler:    _GraphService_AllPaths_Handler,
		},
		{
			MethodName: "Centrality",
			Handler:    _GraphService_Centrality_Handler,
		},
		{
			MethodName: "CommunityDetection",
			Handler:    _GraphService_CommunityDetection_Handler,
		},
		{
			MethodName: "PageRank",
			Handler:    _GraphService_PageRank_Handler,
		},
		{
			MethodName: "ConnectedComponents",
			Handler:    _GraphService_ConnectedComponents_Handler,
		},
		{
			MethodName: "CycleDetection",
			Handler:    _GraphService_CycleDetection_Handler,
		},
		{
			MethodName: "MatchPattern",
			Handler:    _GraphService_MatchPattern_Handler,
		},
		{
			MethodName: "Subgraph",
			Handler:    _GraphService_Subgraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph.proto",
}
