// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: varyd.proto

package varyd

import (
	types "github.com/sqlrest/go-varyd/src/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_UNKNOWN     HealthStatus = 0
	HealthStatus_HEALTHY     HealthStatus = 1
	HealthStatus_DEGRADED    HealthStatus = 2
	HealthStatus_UNHEALTHY   HealthStatus = 3
	HealthStatus_MAINTENANCE HealthStatus = 4
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "DEGRADED",
		3: "UNHEALTHY",
		4: "MAINTENANCE",
	}
	HealthStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"HEALTHY":     1,
		"DEGRADED":    2,
		"UNHEALTHY":   3,
		"MAINTENANCE": 4,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_varyd_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_varyd_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{0}
}

type LogLevel int32

const (
	LogLevel_TRACE LogLevel = 0
	LogLevel_DEBUG LogLevel = 1
	LogLevel_INFO  LogLevel = 2
	LogLevel_WARN  LogLevel = 3
	LogLevel_ERROR LogLevel = 4
	LogLevel_FATAL LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "TRACE",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
		5: "FATAL",
	}
	LogLevel_value = map[string]int32{
		"TRACE": 0,
		"DEBUG": 1,
		"INFO":  2,
		"WARN":  3,
		"ERROR": 4,
		"FATAL": 5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_varyd_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_varyd_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{1}
}

// Common data structures for unified results
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Values        []*types.TypedValue    `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_varyd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Data) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Data) GetValues() []*types.TypedValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Data) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Data) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Data) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_varyd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Link) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Link) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Link) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*Data                `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Links         []*Link                `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Metadata      map[string]*anypb.Any  `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *types.Error           `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_varyd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Result) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Result) GetMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Result) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Common request/response wrappers
type Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context        map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestContext *RequestContext        `protobuf:"bytes,4,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_varyd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Request) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Request) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]*anypb.Any  `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_varyd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Authentication and authorization
type AuthContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthContext) Reset() {
	*x = AuthContext{}
	mi := &file_varyd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthContext) ProtoMessage() {}

func (x *AuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthContext.ProtoReflect.Descriptor instead.
func (*AuthContext) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{5}
}

func (x *AuthContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthContext) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AuthContext) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AuthContext) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *AuthContext) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Auth          *AuthContext           `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_varyd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{6}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetAuth() *AuthContext {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *RequestContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequestContext) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Session management
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthContext   *AuthContext           `protobuf:"bytes,3,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastAccessed  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_varyd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{7}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *Session) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetLastAccessed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessed
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Query execution context
type QueryContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryId        string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SqlDialect     string                 `protobuf:"bytes,3,opt,name=sql_dialect,json=sqlDialect,proto3" json:"sql_dialect,omitempty"`
	TargetServices []string               `protobuf:"bytes,4,rep,name=target_services,json=targetServices,proto3" json:"target_services,omitempty"`
	Options        map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryContext) Reset() {
	*x = QueryContext{}
	mi := &file_varyd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContext) ProtoMessage() {}

func (x *QueryContext) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContext.ProtoReflect.Descriptor instead.
func (*QueryContext) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{8}
}

func (x *QueryContext) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryContext) GetSqlDialect() string {
	if x != nil {
		return x.SqlDialect
	}
	return ""
}

func (x *QueryContext) GetTargetServices() []string {
	if x != nil {
		return x.TargetServices
	}
	return nil
}

func (x *QueryContext) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QueryContext) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Cross-service operation results
type CrossServiceResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ServiceResults []*ServiceResult       `protobuf:"bytes,2,rep,name=service_results,json=serviceResults,proto3" json:"service_results,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error          *types.Error           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrossServiceResult) Reset() {
	*x = CrossServiceResult{}
	mi := &file_varyd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossServiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossServiceResult) ProtoMessage() {}

func (x *CrossServiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossServiceResult.ProtoReflect.Descriptor instead.
func (*CrossServiceResult) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{9}
}

func (x *CrossServiceResult) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CrossServiceResult) GetServiceResults() []*ServiceResult {
	if x != nil {
		return x.ServiceResults
	}
	return nil
}

func (x *CrossServiceResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrossServiceResult) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CrossServiceResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ServiceResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Operation       string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Result          *anypb.Any             `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error           *types.Error           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs float64                `protobuf:"fixed64,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceResult) Reset() {
	*x = ServiceResult{}
	mi := &file_varyd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResult) ProtoMessage() {}

func (x *ServiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResult.ProtoReflect.Descriptor instead.
func (*ServiceResult) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceResult) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceResult) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ServiceResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceResult) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ServiceResult) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServiceResult) GetExecutionTimeMs() float64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

// Health check and service discovery
type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status        HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=varyd.api.v1.HealthStatus" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_varyd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheck) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheck) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

func (x *HealthCheck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheck) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheck) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metrics and observability
type Metrics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServiceName           string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Operation             string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	RequestCount          int64                  `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	AverageResponseTimeMs float64                `protobuf:"fixed64,4,opt,name=average_response_time_ms,json=averageResponseTimeMs,proto3" json:"average_response_time_ms,omitempty"`
	ErrorCount            int64                  `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	SuccessRate           float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	WindowStart           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_varyd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{12}
}

func (x *Metrics) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Metrics) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Metrics) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *Metrics) GetAverageResponseTimeMs() float64 {
	if x != nil {
		return x.AverageResponseTimeMs
	}
	return 0
}

func (x *Metrics) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *Metrics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *Metrics) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *Metrics) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

type TraceSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationMs    int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Logs          []*LogEntry            `protobuf:"bytes,10,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceSpan) Reset() {
	*x = TraceSpan{}
	mi := &file_varyd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceSpan) ProtoMessage() {}

func (x *TraceSpan) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceSpan.ProtoReflect.Descriptor instead.
func (*TraceSpan) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{13}
}

func (x *TraceSpan) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceSpan) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceSpan) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *TraceSpan) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TraceSpan) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TraceSpan) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TraceSpan) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TraceSpan) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TraceSpan) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TraceSpan) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=varyd.api.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_varyd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_varyd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_varyd_proto_rawDescGZIP(), []int{14}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_TRACE
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_varyd_proto protoreflect.FileDescriptor

const file_varyd_proto_rawDesc = "" +
	"\n" +
	"\vvaryd.proto\x12\fvaryd.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\vtypes.proto\"\xd7\x02\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x120\n" +
	"\x06values\x18\x03 \x03(\v2\x18.varyd.api.v1.TypedValueR\x06values\x12B\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2\".varyd.api.v1.Data.PropertiesEntryR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12B\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2\".varyd.api.v1.Link.PropertiesEntryR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\x06Result\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.varyd.api.v1.DataR\x04data\x12(\n" +
	"\x05links\x18\x04 \x03(\v2\x12.varyd.api.v1.LinkR\x05links\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".varyd.api.v1.Result.MetadataEntryR\bmetadata\x12)\n" +
	"\x05error\x18\x06 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\x1aQ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x82\x02\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12<\n" +
	"\acontext\x18\x03 \x03(\v2\".varyd.api.v1.Request.ContextEntryR\acontext\x12E\n" +
	"\x0frequest_context\x18\x04 \x01(\v2\x1c.varyd.api.v1.RequestContextR\x0erequestContext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\bResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.varyd.api.v1.ResultR\x06result\x12@\n" +
	"\bmetadata\x18\x02 \x03(\v2$.varyd.api.v1.Response.MetadataEntryR\bmetadata\x1aQ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x93\x02\n" +
	"\vAuthContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x12=\n" +
	"\x06claims\x18\x04 \x03(\v2%.varyd.api.v1.AuthContext.ClaimsEntryR\x06claims\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x02\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\x04auth\x18\x02 \x01(\v2\x19.varyd.api.v1.AuthContextR\x04auth\x12F\n" +
	"\bmetadata\x18\x03 \x03(\v2*.varyd.api.v1.RequestContext.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x03\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12<\n" +
	"\fauth_context\x18\x03 \x01(\v2\x19.varyd.api.v1.AuthContextR\vauthContext\x12E\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2%.varyd.api.v1.Session.PropertiesEntryR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\rlast_accessed\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessed\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\fQueryContext\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vsql_dialect\x18\x03 \x01(\tR\n" +
	"sqlDialect\x12'\n" +
	"\x0ftarget_services\x18\x04 \x03(\tR\x0etargetServices\x12A\n" +
	"\aoptions\x18\x05 \x03(\v2'.varyd.api.v1.QueryContext.OptionsEntryR\aoptions\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\x12CrossServiceResult\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12D\n" +
	"\x0fservice_results\x18\x02 \x03(\v2\x1b.varyd.api.v1.ServiceResultR\x0eserviceResults\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12)\n" +
	"\x05error\x18\x04 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xef\x01\n" +
	"\rServiceResult\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12,\n" +
	"\x06result\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x06result\x12)\n" +
	"\x05error\x18\x05 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x01R\x0fexecutionTimeMs\"\xba\x02\n" +
	"\vHealthCheck\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.varyd.api.v1.HealthStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.varyd.api.v1.HealthCheck.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x02\n" +
	"\aMetrics\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x127\n" +
	"\x18average_response_time_ms\x18\x04 \x01(\x01R\x15averageResponseTimeMs\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x03R\n" +
	"errorCount\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\x12=\n" +
	"\fwindow_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\"\xd5\x03\n" +
	"\tTraceSpan\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x125\n" +
	"\x04tags\x18\t \x03(\v2!.varyd.api.v1.TraceSpan.TagsEntryR\x04tags\x12*\n" +
	"\x04logs\x18\n" +
	" \x03(\v2\x16.varyd.api.v1.LogEntryR\x04logs\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x05level\x18\x02 \x01(\x0e2\x16.varyd.api.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12:\n" +
	"\x06fields\x18\x04 \x03(\v2\".varyd.api.v1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*V\n" +
	"\fHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\f\n" +
	"\bDEGRADED\x10\x02\x12\r\n" +
	"\tUNHEALTHY\x10\x03\x12\x0f\n" +
	"\vMAINTENANCE\x10\x04*J\n" +
	"\bLogLevel\x12\t\n" +
	"\x05TRACE\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\t\n" +
	"\x05FATAL\x10\x05B-Z+github.com/sqlrest/go-varyd/src/proto/varydb\x06proto3"

var (
	file_varyd_proto_rawDescOnce sync.Once
	file_varyd_proto_rawDescData []byte
)

func file_varyd_proto_rawDescGZIP() []byte {
	file_varyd_proto_rawDescOnce.Do(func() {
		file_varyd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_varyd_proto_rawDesc), len(file_varyd_proto_rawDesc)))
	})
	return file_varyd_proto_rawDescData
}

var file_varyd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_varyd_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_varyd_proto_goTypes = []any{
	(HealthStatus)(0),             // 0: varyd.api.v1.HealthStatus
	(LogLevel)(0),                 // 1: varyd.api.v1.LogLevel
	(*Data)(nil),                  // 2: varyd.api.v1.Data
	(*Link)(nil),                  // 3: varyd.api.v1.Link
	(*Result)(nil),                // 4: varyd.api.v1.Result
	(*Request)(nil),               // 5: varyd.api.v1.Request
	(*Response)(nil),              // 6: varyd.api.v1.Response
	(*AuthContext)(nil),           // 7: varyd.api.v1.AuthContext
	(*RequestContext)(nil),        // 8: varyd.api.v1.RequestContext
	(*Session)(nil),               // 9: varyd.api.v1.Session
	(*QueryContext)(nil),          // 10: varyd.api.v1.QueryContext
	(*CrossServiceResult)(nil),    // 11: varyd.api.v1.CrossServiceResult
	(*ServiceResult)(nil),         // 12: varyd.api.v1.ServiceResult
	(*HealthCheck)(nil),           // 13: varyd.api.v1.HealthCheck
	(*Metrics)(nil),               // 14: varyd.api.v1.Metrics
	(*TraceSpan)(nil),             // 15: varyd.api.v1.TraceSpan
	(*LogEntry)(nil),              // 16: varyd.api.v1.LogEntry
	nil,                           // 17: varyd.api.v1.Data.PropertiesEntry
	nil,                           // 18: varyd.api.v1.Link.PropertiesEntry
	nil,                           // 19: varyd.api.v1.Result.MetadataEntry
	nil,                           // 20: varyd.api.v1.Request.ContextEntry
	nil,                           // 21: varyd.api.v1.Response.MetadataEntry
	nil,                           // 22: varyd.api.v1.AuthContext.ClaimsEntry
	nil,                           // 23: varyd.api.v1.RequestContext.MetadataEntry
	nil,                           // 24: varyd.api.v1.Session.PropertiesEntry
	nil,                           // 25: varyd.api.v1.QueryContext.OptionsEntry
	nil,                           // 26: varyd.api.v1.HealthCheck.MetadataEntry
	nil,                           // 27: varyd.api.v1.TraceSpan.TagsEntry
	nil,                           // 28: varyd.api.v1.LogEntry.FieldsEntry
	(*types.TypedValue)(nil),      // 29: varyd.api.v1.TypedValue
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
	(*types.Error)(nil),           // 31: varyd.api.v1.Error
	(*anypb.Any)(nil),             // 32: google.protobuf.Any
}
var file_varyd_proto_depIdxs = []int32{
	29, // 0: varyd.api.v1.Data.values:type_name -> varyd.api.v1.TypedValue
	17, // 1: varyd.api.v1.Data.properties:type_name -> varyd.api.v1.Data.PropertiesEntry
	30, // 2: varyd.api.v1.Data.created_at:type_name -> google.protobuf.Timestamp
	30, // 3: varyd.api.v1.Data.updated_at:type_name -> google.protobuf.Timestamp
	18, // 4: varyd.api.v1.Link.properties:type_name -> varyd.api.v1.Link.PropertiesEntry
	30, // 5: varyd.api.v1.Link.created_at:type_name -> google.protobuf.Timestamp
	2,  // 6: varyd.api.v1.Result.data:type_name -> varyd.api.v1.Data
	3,  // 7: varyd.api.v1.Result.links:type_name -> varyd.api.v1.Link
	19, // 8: varyd.api.v1.Result.metadata:type_name -> varyd.api.v1.Result.MetadataEntry
	31, // 9: varyd.api.v1.Result.error:type_name -> varyd.api.v1.Error
	20, // 10: varyd.api.v1.Request.context:type_name -> varyd.api.v1.Request.ContextEntry
	8,  // 11: varyd.api.v1.Request.request_context:type_name -> varyd.api.v1.RequestContext
	4,  // 12: varyd.api.v1.Response.result:type_name -> varyd.api.v1.Result
	21, // 13: varyd.api.v1.Response.metadata:type_name -> varyd.api.v1.Response.MetadataEntry
	22, // 14: varyd.api.v1.AuthContext.claims:type_name -> varyd.api.v1.AuthContext.ClaimsEntry
	30, // 15: varyd.api.v1.AuthContext.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 16: varyd.api.v1.RequestContext.auth:type_name -> varyd.api.v1.AuthContext
	23, // 17: varyd.api.v1.RequestContext.metadata:type_name -> varyd.api.v1.RequestContext.MetadataEntry
	30, // 18: varyd.api.v1.RequestContext.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 19: varyd.api.v1.Session.auth_context:type_name -> varyd.api.v1.AuthContext
	24, // 20: varyd.api.v1.Session.properties:type_name -> varyd.api.v1.Session.PropertiesEntry
	30, // 21: varyd.api.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	30, // 22: varyd.api.v1.Session.last_accessed:type_name -> google.protobuf.Timestamp
	30, // 23: varyd.api.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	25, // 24: varyd.api.v1.QueryContext.options:type_name -> varyd.api.v1.QueryContext.OptionsEntry
	30, // 25: varyd.api.v1.QueryContext.started_at:type_name -> google.protobuf.Timestamp
	12, // 26: varyd.api.v1.CrossServiceResult.service_results:type_name -> varyd.api.v1.ServiceResult
	31, // 27: varyd.api.v1.CrossServiceResult.error:type_name -> varyd.api.v1.Error
	30, // 28: varyd.api.v1.CrossServiceResult.completed_at:type_name -> google.protobuf.Timestamp
	32, // 29: varyd.api.v1.ServiceResult.result:type_name -> google.protobuf.Any
	31, // 30: varyd.api.v1.ServiceResult.error:type_name -> varyd.api.v1.Error
	0,  // 31: varyd.api.v1.HealthCheck.status:type_name -> varyd.api.v1.HealthStatus
	30, // 32: varyd.api.v1.HealthCheck.timestamp:type_name -> google.protobuf.Timestamp
	26, // 33: varyd.api.v1.HealthCheck.metadata:type_name -> varyd.api.v1.HealthCheck.MetadataEntry
	30, // 34: varyd.api.v1.Metrics.window_start:type_name -> google.protobuf.Timestamp
	30, // 35: varyd.api.v1.Metrics.window_end:type_name -> google.protobuf.Timestamp
	30, // 36: varyd.api.v1.TraceSpan.start_time:type_name -> google.protobuf.Timestamp
	30, // 37: varyd.api.v1.TraceSpan.end_time:type_name -> google.protobuf.Timestamp
	27, // 38: varyd.api.v1.TraceSpan.tags:type_name -> varyd.api.v1.TraceSpan.TagsEntry
	16, // 39: varyd.api.v1.TraceSpan.logs:type_name -> varyd.api.v1.LogEntry
	30, // 40: varyd.api.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 41: varyd.api.v1.LogEntry.level:type_name -> varyd.api.v1.LogLevel
	28, // 42: varyd.api.v1.LogEntry.fields:type_name -> varyd.api.v1.LogEntry.FieldsEntry
	32, // 43: varyd.api.v1.Result.MetadataEntry.value:type_name -> google.protobuf.Any
	32, // 44: varyd.api.v1.Response.MetadataEntry.value:type_name -> google.protobuf.Any
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_varyd_proto_init() }
func file_varyd_proto_init() {
	if File_varyd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_varyd_proto_rawDesc), len(file_varyd_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_varyd_proto_goTypes,
		DependencyIndexes: file_varyd_proto_depIdxs,
		EnumInfos:         file_varyd_proto_enumTypes,
		MessageInfos:      file_varyd_proto_msgTypes,
	}.Build()
	File_varyd_proto = out.File
	file_varyd_proto_goTypes = nil
	file_varyd_proto_depIdxs = nil
}
