// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: spatial.proto

package spatial

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpatialService_CreateGeometry_FullMethodName     = "/varyd.api.v1.SpatialService/CreateGeometry"
	SpatialService_GetGeometry_FullMethodName        = "/varyd.api.v1.SpatialService/GetGeometry"
	SpatialService_UpdateGeometry_FullMethodName     = "/varyd.api.v1.SpatialService/UpdateGeometry"
	SpatialService_DeleteGeometry_FullMethodName     = "/varyd.api.v1.SpatialService/DeleteGeometry"
	SpatialService_ListGeometries_FullMethodName     = "/varyd.api.v1.SpatialService/ListGeometries"
	SpatialService_Query_FullMethodName              = "/varyd.api.v1.SpatialService/Query"
	SpatialService_Within_FullMethodName             = "/varyd.api.v1.SpatialService/Within"
	SpatialService_Intersects_FullMethodName         = "/varyd.api.v1.SpatialService/Intersects"
	SpatialService_Contains_FullMethodName           = "/varyd.api.v1.SpatialService/Contains"
	SpatialService_Touches_FullMethodName            = "/varyd.api.v1.SpatialService/Touches"
	SpatialService_Crosses_FullMethodName            = "/varyd.api.v1.SpatialService/Crosses"
	SpatialService_Overlaps_FullMethodName           = "/varyd.api.v1.SpatialService/Overlaps"
	SpatialService_Distance_FullMethodName           = "/varyd.api.v1.SpatialService/Distance"
	SpatialService_Nearest_FullMethodName            = "/varyd.api.v1.SpatialService/Nearest"
	SpatialService_Buffer_FullMethodName             = "/varyd.api.v1.SpatialService/Buffer"
	SpatialService_Union_FullMethodName              = "/varyd.api.v1.SpatialService/Union"
	SpatialService_Intersection_FullMethodName       = "/varyd.api.v1.SpatialService/Intersection"
	SpatialService_Difference_FullMethodName         = "/varyd.api.v1.SpatialService/Difference"
	SpatialService_ConvexHull_FullMethodName         = "/varyd.api.v1.SpatialService/ConvexHull"
	SpatialService_Simplify_FullMethodName           = "/varyd.api.v1.SpatialService/Simplify"
	SpatialService_CreateSpatialIndex_FullMethodName = "/varyd.api.v1.SpatialService/CreateSpatialIndex"
	SpatialService_DeleteSpatialIndex_FullMethodName = "/varyd.api.v1.SpatialService/DeleteSpatialIndex"
	SpatialService_ListSpatialIndexes_FullMethodName = "/varyd.api.v1.SpatialService/ListSpatialIndexes"
	SpatialService_IndexQuery_FullMethodName         = "/varyd.api.v1.SpatialService/IndexQuery"
	SpatialService_Transform_FullMethodName          = "/varyd.api.v1.SpatialService/Transform"
	SpatialService_GetSRSInfo_FullMethodName         = "/varyd.api.v1.SpatialService/GetSRSInfo"
)

// SpatialServiceClient is the client API for SpatialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpatialServiceClient interface {
	// Geometry operations
	CreateGeometry(ctx context.Context, in *CreateGeometryRequest, opts ...grpc.CallOption) (*CreateGeometryResponse, error)
	GetGeometry(ctx context.Context, in *GetGeometryRequest, opts ...grpc.CallOption) (*GetGeometryResponse, error)
	UpdateGeometry(ctx context.Context, in *UpdateGeometryRequest, opts ...grpc.CallOption) (*UpdateGeometryResponse, error)
	DeleteGeometry(ctx context.Context, in *DeleteGeometryRequest, opts ...grpc.CallOption) (*DeleteGeometryResponse, error)
	ListGeometries(ctx context.Context, in *ListGeometriesRequest, opts ...grpc.CallOption) (*ListGeometriesResponse, error)
	// Spatial queries
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Within(ctx context.Context, in *WithinRequest, opts ...grpc.CallOption) (*WithinResponse, error)
	Intersects(ctx context.Context, in *IntersectsRequest, opts ...grpc.CallOption) (*IntersectsResponse, error)
	Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error)
	Touches(ctx context.Context, in *TouchesRequest, opts ...grpc.CallOption) (*TouchesResponse, error)
	Crosses(ctx context.Context, in *CrossesRequest, opts ...grpc.CallOption) (*CrossesResponse, error)
	Overlaps(ctx context.Context, in *OverlapsRequest, opts ...grpc.CallOption) (*OverlapsResponse, error)
	Distance(ctx context.Context, in *DistanceRequest, opts ...grpc.CallOption) (*DistanceResponse, error)
	Nearest(ctx context.Context, in *NearestRequest, opts ...grpc.CallOption) (*NearestResponse, error)
	// Spatial operations
	Buffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*BufferResponse, error)
	Union(ctx context.Context, in *UnionRequest, opts ...grpc.CallOption) (*UnionResponse, error)
	Intersection(ctx context.Context, in *IntersectionRequest, opts ...grpc.CallOption) (*IntersectionResponse, error)
	Difference(ctx context.Context, in *DifferenceRequest, opts ...grpc.CallOption) (*DifferenceResponse, error)
	ConvexHull(ctx context.Context, in *ConvexHullRequest, opts ...grpc.CallOption) (*ConvexHullResponse, error)
	Simplify(ctx context.Context, in *SimplifyRequest, opts ...grpc.CallOption) (*SimplifyResponse, error)
	// Spatial indexing
	CreateSpatialIndex(ctx context.Context, in *CreateSpatialIndexRequest, opts ...grpc.CallOption) (*CreateSpatialIndexResponse, error)
	DeleteSpatialIndex(ctx context.Context, in *DeleteSpatialIndexRequest, opts ...grpc.CallOption) (*DeleteSpatialIndexResponse, error)
	ListSpatialIndexes(ctx context.Context, in *ListSpatialIndexesRequest, opts ...grpc.CallOption) (*ListSpatialIndexesResponse, error)
	IndexQuery(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*IndexQueryResponse, error)
	// Coordinate transformation
	Transform(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error)
	GetSRSInfo(ctx context.Context, in *GetSRSInfoRequest, opts ...grpc.CallOption) (*GetSRSInfoResponse, error)
}

type spatialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpatialServiceClient(cc grpc.ClientConnInterface) SpatialServiceClient {
	return &spatialServiceClient{cc}
}

func (c *spatialServiceClient) CreateGeometry(ctx context.Context, in *CreateGeometryRequest, opts ...grpc.CallOption) (*CreateGeometryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGeometryResponse)
	err := c.cc.Invoke(ctx, SpatialService_CreateGeometry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) GetGeometry(ctx context.Context, in *GetGeometryRequest, opts ...grpc.CallOption) (*GetGeometryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGeometryResponse)
	err := c.cc.Invoke(ctx, SpatialService_GetGeometry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) UpdateGeometry(ctx context.Context, in *UpdateGeometryRequest, opts ...grpc.CallOption) (*UpdateGeometryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGeometryResponse)
	err := c.cc.Invoke(ctx, SpatialService_UpdateGeometry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) DeleteGeometry(ctx context.Context, in *DeleteGeometryRequest, opts ...grpc.CallOption) (*DeleteGeometryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGeometryResponse)
	err := c.cc.Invoke(ctx, SpatialService_DeleteGeometry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) ListGeometries(ctx context.Context, in *ListGeometriesRequest, opts ...grpc.CallOption) (*ListGeometriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGeometriesResponse)
	err := c.cc.Invoke(ctx, SpatialService_ListGeometries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, SpatialService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Within(ctx context.Context, in *WithinRequest, opts ...grpc.CallOption) (*WithinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithinResponse)
	err := c.cc.Invoke(ctx, SpatialService_Within_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Intersects(ctx context.Context, in *IntersectsRequest, opts ...grpc.CallOption) (*IntersectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntersectsResponse)
	err := c.cc.Invoke(ctx, SpatialService_Intersects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainsResponse)
	err := c.cc.Invoke(ctx, SpatialService_Contains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Touches(ctx context.Context, in *TouchesRequest, opts ...grpc.CallOption) (*TouchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TouchesResponse)
	err := c.cc.Invoke(ctx, SpatialService_Touches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Crosses(ctx context.Context, in *CrossesRequest, opts ...grpc.CallOption) (*CrossesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrossesResponse)
	err := c.cc.Invoke(ctx, SpatialService_Crosses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Overlaps(ctx context.Context, in *OverlapsRequest, opts ...grpc.CallOption) (*OverlapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverlapsResponse)
	err := c.cc.Invoke(ctx, SpatialService_Overlaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Distance(ctx context.Context, in *DistanceRequest, opts ...grpc.CallOption) (*DistanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistanceResponse)
	err := c.cc.Invoke(ctx, SpatialService_Distance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Nearest(ctx context.Context, in *NearestRequest, opts ...grpc.CallOption) (*NearestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NearestResponse)
	err := c.cc.Invoke(ctx, SpatialService_Nearest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Buffer(ctx context.Context, in *BufferRequest, opts ...grpc.CallOption) (*BufferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BufferResponse)
	err := c.cc.Invoke(ctx, SpatialService_Buffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Union(ctx context.Context, in *UnionRequest, opts ...grpc.CallOption) (*UnionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnionResponse)
	err := c.cc.Invoke(ctx, SpatialService_Union_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Intersection(ctx context.Context, in *IntersectionRequest, opts ...grpc.CallOption) (*IntersectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntersectionResponse)
	err := c.cc.Invoke(ctx, SpatialService_Intersection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Difference(ctx context.Context, in *DifferenceRequest, opts ...grpc.CallOption) (*DifferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DifferenceResponse)
	err := c.cc.Invoke(ctx, SpatialService_Difference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) ConvexHull(ctx context.Context, in *ConvexHullRequest, opts ...grpc.CallOption) (*ConvexHullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvexHullResponse)
	err := c.cc.Invoke(ctx, SpatialService_ConvexHull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Simplify(ctx context.Context, in *SimplifyRequest, opts ...grpc.CallOption) (*SimplifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimplifyResponse)
	err := c.cc.Invoke(ctx, SpatialService_Simplify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) CreateSpatialIndex(ctx context.Context, in *CreateSpatialIndexRequest, opts ...grpc.CallOption) (*CreateSpatialIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSpatialIndexResponse)
	err := c.cc.Invoke(ctx, SpatialService_CreateSpatialIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) DeleteSpatialIndex(ctx context.Context, in *DeleteSpatialIndexRequest, opts ...grpc.CallOption) (*DeleteSpatialIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSpatialIndexResponse)
	err := c.cc.Invoke(ctx, SpatialService_DeleteSpatialIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) ListSpatialIndexes(ctx context.Context, in *ListSpatialIndexesRequest, opts ...grpc.CallOption) (*ListSpatialIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpatialIndexesResponse)
	err := c.cc.Invoke(ctx, SpatialService_ListSpatialIndexes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) IndexQuery(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*IndexQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexQueryResponse)
	err := c.cc.Invoke(ctx, SpatialService_IndexQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) Transform(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformResponse)
	err := c.cc.Invoke(ctx, SpatialService_Transform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spatialServiceClient) GetSRSInfo(ctx context.Context, in *GetSRSInfoRequest, opts ...grpc.CallOption) (*GetSRSInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSRSInfoResponse)
	err := c.cc.Invoke(ctx, SpatialService_GetSRSInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpatialServiceServer is the server API for SpatialService service.
// All implementations must embed UnimplementedSpatialServiceServer
// for forward compatibility.
type SpatialServiceServer interface {
	// Geometry operations
	CreateGeometry(context.Context, *CreateGeometryRequest) (*CreateGeometryResponse, error)
	GetGeometry(context.Context, *GetGeometryRequest) (*GetGeometryResponse, error)
	UpdateGeometry(context.Context, *UpdateGeometryRequest) (*UpdateGeometryResponse, error)
	DeleteGeometry(context.Context, *DeleteGeometryRequest) (*DeleteGeometryResponse, error)
	ListGeometries(context.Context, *ListGeometriesRequest) (*ListGeometriesResponse, error)
	// Spatial queries
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Within(context.Context, *WithinRequest) (*WithinResponse, error)
	Intersects(context.Context, *IntersectsRequest) (*IntersectsResponse, error)
	Contains(context.Context, *ContainsRequest) (*ContainsResponse, error)
	Touches(context.Context, *TouchesRequest) (*TouchesResponse, error)
	Crosses(context.Context, *CrossesRequest) (*CrossesResponse, error)
	Overlaps(context.Context, *OverlapsRequest) (*OverlapsResponse, error)
	Distance(context.Context, *DistanceRequest) (*DistanceResponse, error)
	Nearest(context.Context, *NearestRequest) (*NearestResponse, error)
	// Spatial operations
	Buffer(context.Context, *BufferRequest) (*BufferResponse, error)
	Union(context.Context, *UnionRequest) (*UnionResponse, error)
	Intersection(context.Context, *IntersectionRequest) (*IntersectionResponse, error)
	Difference(context.Context, *DifferenceRequest) (*DifferenceResponse, error)
	ConvexHull(context.Context, *ConvexHullRequest) (*ConvexHullResponse, error)
	Simplify(context.Context, *SimplifyRequest) (*SimplifyResponse, error)
	// Spatial indexing
	CreateSpatialIndex(context.Context, *CreateSpatialIndexRequest) (*CreateSpatialIndexResponse, error)
	DeleteSpatialIndex(context.Context, *DeleteSpatialIndexRequest) (*DeleteSpatialIndexResponse, error)
	ListSpatialIndexes(context.Context, *ListSpatialIndexesRequest) (*ListSpatialIndexesResponse, error)
	IndexQuery(context.Context, *IndexQueryRequest) (*IndexQueryResponse, error)
	// Coordinate transformation
	Transform(context.Context, *TransformRequest) (*TransformResponse, error)
	GetSRSInfo(context.Context, *GetSRSInfoRequest) (*GetSRSInfoResponse, error)
	mustEmbedUnimplementedSpatialServiceServer()
}

// UnimplementedSpatialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpatialServiceServer struct{}

func (UnimplementedSpatialServiceServer) CreateGeometry(context.Context, *CreateGeometryRequest) (*CreateGeometryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGeometry not implemented")
}
func (UnimplementedSpatialServiceServer) GetGeometry(context.Context, *GetGeometryRequest) (*GetGeometryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGeometry not implemented")
}
func (UnimplementedSpatialServiceServer) UpdateGeometry(context.Context, *UpdateGeometryRequest) (*UpdateGeometryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGeometry not implemented")
}
func (UnimplementedSpatialServiceServer) DeleteGeometry(context.Context, *DeleteGeometryRequest) (*DeleteGeometryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGeometry not implemented")
}
func (UnimplementedSpatialServiceServer) ListGeometries(context.Context, *ListGeometriesRequest) (*ListGeometriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGeometries not implemented")
}
func (UnimplementedSpatialServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSpatialServiceServer) Within(context.Context, *WithinRequest) (*WithinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Within not implemented")
}
func (UnimplementedSpatialServiceServer) Intersects(context.Context, *IntersectsRequest) (*IntersectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Intersects not implemented")
}
func (UnimplementedSpatialServiceServer) Contains(context.Context, *ContainsRequest) (*ContainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Contains not implemented")
}
func (UnimplementedSpatialServiceServer) Touches(context.Context, *TouchesRequest) (*TouchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Touches not implemented")
}
func (UnimplementedSpatialServiceServer) Crosses(context.Context, *CrossesRequest) (*CrossesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Crosses not implemented")
}
func (UnimplementedSpatialServiceServer) Overlaps(context.Context, *OverlapsRequest) (*OverlapsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Overlaps not implemented")
}
func (UnimplementedSpatialServiceServer) Distance(context.Context, *DistanceRequest) (*DistanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Distance not implemented")
}
func (UnimplementedSpatialServiceServer) Nearest(context.Context, *NearestRequest) (*NearestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Nearest not implemented")
}
func (UnimplementedSpatialServiceServer) Buffer(context.Context, *BufferRequest) (*BufferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Buffer not implemented")
}
func (UnimplementedSpatialServiceServer) Union(context.Context, *UnionRequest) (*UnionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Union not implemented")
}
func (UnimplementedSpatialServiceServer) Intersection(context.Context, *IntersectionRequest) (*IntersectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Intersection not implemented")
}
func (UnimplementedSpatialServiceServer) Difference(context.Context, *DifferenceRequest) (*DifferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Difference not implemented")
}
func (UnimplementedSpatialServiceServer) ConvexHull(context.Context, *ConvexHullRequest) (*ConvexHullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvexHull not implemented")
}
func (UnimplementedSpatialServiceServer) Simplify(context.Context, *SimplifyRequest) (*SimplifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Simplify not implemented")
}
func (UnimplementedSpatialServiceServer) CreateSpatialIndex(context.Context, *CreateSpatialIndexRequest) (*CreateSpatialIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpatialIndex not implemented")
}
func (UnimplementedSpatialServiceServer) DeleteSpatialIndex(context.Context, *DeleteSpatialIndexRequest) (*DeleteSpatialIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSpatialIndex not implemented")
}
func (UnimplementedSpatialServiceServer) ListSpatialIndexes(context.Context, *ListSpatialIndexesRequest) (*ListSpatialIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpatialIndexes not implemented")
}
func (UnimplementedSpatialServiceServer) IndexQuery(context.Context, *IndexQueryRequest) (*IndexQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexQuery not implemented")
}
func (UnimplementedSpatialServiceServer) Transform(context.Context, *TransformRequest) (*TransformResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transform not implemented")
}
func (UnimplementedSpatialServiceServer) GetSRSInfo(context.Context, *GetSRSInfoRequest) (*GetSRSInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSRSInfo not implemented")
}
func (UnimplementedSpatialServiceServer) mustEmbedUnimplementedSpatialServiceServer() {}
func (UnimplementedSpatialServiceServer) testEmbeddedByValue()                        {}

// UnsafeSpatialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpatialServiceServer will
// result in compilation errors.
type UnsafeSpatialServiceServer interface {
	mustEmbedUnimplementedSpatialServiceServer()
}

func RegisterSpatialServiceServer(s grpc.ServiceRegistrar, srv SpatialServiceServer) {
	// If the following call panics, it indicates UnimplementedSpatialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpatialService_ServiceDesc, srv)
}

func _SpatialService_CreateGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).CreateGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_CreateGeometry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).CreateGeometry(ctx, req.(*CreateGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_GetGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).GetGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_GetGeometry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).GetGeometry(ctx, req.(*GetGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_UpdateGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).UpdateGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_UpdateGeometry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).UpdateGeometry(ctx, req.(*UpdateGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_DeleteGeometry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGeometryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).DeleteGeometry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_DeleteGeometry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).DeleteGeometry(ctx, req.(*DeleteGeometryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_ListGeometries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGeometriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).ListGeometries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_ListGeometries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).ListGeometries(ctx, req.(*ListGeometriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Within_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Within(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Within_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Within(ctx, req.(*WithinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Intersects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntersectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Intersects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Intersects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Intersects(ctx, req.(*IntersectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Contains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Contains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Contains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Contains(ctx, req.(*ContainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Touches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Touches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Touches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Touches(ctx, req.(*TouchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Crosses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Crosses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Crosses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Crosses(ctx, req.(*CrossesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Overlaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverlapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Overlaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Overlaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Overlaps(ctx, req.(*OverlapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Distance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Distance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Distance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Distance(ctx, req.(*DistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Nearest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Nearest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Nearest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Nearest(ctx, req.(*NearestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Buffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BufferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Buffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Buffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Buffer(ctx, req.(*BufferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Union_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Union(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Union_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Union(ctx, req.(*UnionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Intersection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntersectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Intersection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Intersection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Intersection(ctx, req.(*IntersectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Difference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DifferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Difference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Difference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Difference(ctx, req.(*DifferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_ConvexHull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvexHullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).ConvexHull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_ConvexHull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).ConvexHull(ctx, req.(*ConvexHullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Simplify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimplifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Simplify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Simplify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Simplify(ctx, req.(*SimplifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_CreateSpatialIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpatialIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).CreateSpatialIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_CreateSpatialIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).CreateSpatialIndex(ctx, req.(*CreateSpatialIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_DeleteSpatialIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpatialIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).DeleteSpatialIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_DeleteSpatialIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).DeleteSpatialIndex(ctx, req.(*DeleteSpatialIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_ListSpatialIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpatialIndexesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).ListSpatialIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_ListSpatialIndexes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).ListSpatialIndexes(ctx, req.(*ListSpatialIndexesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_IndexQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).IndexQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_IndexQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).IndexQuery(ctx, req.(*IndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_Transform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).Transform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_Transform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).Transform(ctx, req.(*TransformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpatialService_GetSRSInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSRSInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpatialServiceServer).GetSRSInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpatialService_GetSRSInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpatialServiceServer).GetSRSInfo(ctx, req.(*GetSRSInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpatialService_ServiceDesc is the grpc.ServiceDesc for SpatialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpatialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "varyd.api.v1.SpatialService",
	HandlerType: (*SpatialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGeometry",
			Handler:    _SpatialService_CreateGeometry_Handler,
		},
		{
			MethodName: "GetGeometry",
			Handler:    _SpatialService_GetGeometry_Handler,
		},
		{
			MethodName: "UpdateGeometry",
			Handler:    _SpatialService_UpdateGeometry_Handler,
		},
		{
			MethodName: "DeleteGeometry",
			Handler:    _SpatialService_DeleteGeometry_Handler,
		},
		{
			MethodName: "ListGeometries",
			Handler:    _SpatialService_ListGeometries_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _SpatialService_Query_Handler,
		},
		{
			MethodName: "Within",
			Handler:    _SpatialService_Within_Handler,
		},
		{
			MethodName: "Intersects",
			Handler:    _SpatialService_Intersects_Handler,
		},
		{
			MethodName: "Contains",
			Handler:    _SpatialService_Contains_Handler,
		},
		{
			MethodName: "Touches",
			Handler:    _SpatialService_Touches_Handler,
		},
		{
			MethodName: "Crosses",
			Handler:    _SpatialService_Crosses_Handler,
		},
		{
			MethodName: "Overlaps",
			Handler:    _SpatialService_Overlaps_Handler,
		},
		{
			MethodName: "Distance",
			Handler:    _SpatialService_Distance_Handler,
		},
		{
			MethodName: "Nearest",
			Handler:    _SpatialService_Nearest_Handler,
		},
		{
			MethodName: "Buffer",
			Handler:    _SpatialService_Buffer_Handler,
		},
		{
			MethodName: "Union",
			Handler:    _SpatialService_Union_Handler,
		},
		{
			MethodName: "Intersection",
			Handler:    _SpatialService_Intersection_Handler,
		},
		{
			MethodName: "Difference",
			Handler:    _SpatialService_Difference_Handler,
		},
		{
			MethodName: "ConvexHull",
			Handler:    _SpatialService_ConvexHull_Handler,
		},
		{
			MethodName: "Simplify",
			Handler:    _SpatialService_Simplify_Handler,
		},
		{
			MethodName: "CreateSpatialIndex",
			Handler:    _SpatialService_CreateSpatialIndex_Handler,
		},
		{
			MethodName: "DeleteSpatialIndex",
			Handler:    _SpatialService_DeleteSpatialIndex_Handler,
		},
		{
			MethodName: "ListSpatialIndexes",
			Handler:    _SpatialService_ListSpatialIndexes_Handler,
		},
		{
			MethodName: "IndexQuery",
			Handler:    _SpatialService_IndexQuery_Handler,
		},
		{
			MethodName: "Transform",
			Handler:    _SpatialService_Transform_Handler,
		},
		{
			MethodName: "GetSRSInfo",
			Handler:    _SpatialService_GetSRSInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spatial.proto",
}
