// DocumentService proto contract for VaryD PoC
// This file defines the gRPC service for document/collection operations (DocSQL dialect).
// To be placed at api/proto/document.proto during implementation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: document.proto

package document

import (
	types "github.com/sqlrest/go-varyd/src/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IfNotExists   bool                   `protobuf:"varint,2,opt,name=if_not_exists,json=ifNotExists,proto3" json:"if_not_exists,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetIfNotExists() bool {
	if x != nil {
		return x.IfNotExists
	}
	return false
}

func (x *CreateCollectionRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *types.Error           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCollectionResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DropCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IfExists      bool                   `protobuf:"varint,2,opt,name=if_exists,json=ifExists,proto3" json:"if_exists,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionRequest) Reset() {
	*x = DropCollectionRequest{}
	mi := &file_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionRequest) ProtoMessage() {}

func (x *DropCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionRequest.ProtoReflect.Descriptor instead.
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{2}
}

func (x *DropCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DropCollectionRequest) GetIfExists() bool {
	if x != nil {
		return x.IfExists
	}
	return false
}

func (x *DropCollectionRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type DropCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *types.Error           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionResponse) Reset() {
	*x = DropCollectionResponse{}
	mi := &file_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionResponse) ProtoMessage() {}

func (x *DropCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionResponse.ProtoReflect.Descriptor instead.
func (*DropCollectionResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{3}
}

func (x *DropCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DropCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DropCollectionResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DescribeCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCollectionRequest) Reset() {
	*x = DescribeCollectionRequest{}
	mi := &file_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCollectionRequest) ProtoMessage() {}

func (x *DescribeCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCollectionRequest.ProtoReflect.Descriptor instead.
func (*DescribeCollectionRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeCollectionRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type DescribeCollectionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DocumentCount  int64                  `protobuf:"varint,3,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	IndexTermCount int64                  `protobuf:"varint,4,opt,name=index_term_count,json=indexTermCount,proto3" json:"index_term_count,omitempty"`
	Error          *types.Error           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeCollectionResponse) Reset() {
	*x = DescribeCollectionResponse{}
	mi := &file_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCollectionResponse) ProtoMessage() {}

func (x *DescribeCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCollectionResponse.ProtoReflect.Descriptor instead.
func (*DescribeCollectionResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DescribeCollectionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeCollectionResponse) GetDocumentCount() int64 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *DescribeCollectionResponse) GetIndexTermCount() int64 {
	if x != nil {
		return x.IndexTermCount
	}
	return 0
}

func (x *DescribeCollectionResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       map[string]string      `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{6}
}

func (x *ListCollectionsRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Error         *types.Error           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{7}
}

func (x *ListCollectionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListCollectionsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *ListCollectionsResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type InsertDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ContentJson   string                 `protobuf:"bytes,3,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentRequest) Reset() {
	*x = InsertDocumentRequest{}
	mi := &file_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentRequest) ProtoMessage() {}

func (x *InsertDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentRequest.ProtoReflect.Descriptor instead.
func (*InsertDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{8}
}

func (x *InsertDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *InsertDocumentRequest) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *InsertDocumentRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type InsertDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Error         *types.Error           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentResponse) Reset() {
	*x = InsertDocumentResponse{}
	mi := &file_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentResponse) ProtoMessage() {}

func (x *InsertDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentResponse.ProtoReflect.Descriptor instead.
func (*InsertDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{9}
}

func (x *InsertDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *InsertDocumentResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ContentJson   string                 `protobuf:"bytes,3,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Error         *types.Error           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{11}
}

func (x *GetDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentResponse) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *GetDocumentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetDocumentResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ContentJson   string                 `protobuf:"bytes,3,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_document_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *UpdateDocumentRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type UpdateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Error         *types.Error           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_document_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_document_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DeleteDocumentRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *types.Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_document_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDocumentResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Boost         map[string]float32     `protobuf:"bytes,4,rep,name=boost,proto3" json:"boost,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	MinScore      float32                `protobuf:"fixed32,5,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	Options       map[string]string      `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_document_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{16}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchRequest) GetBoost() map[string]float32 {
	if x != nil {
		return x.Boost
	}
	return nil
}

func (x *SearchRequest) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	TotalMatches  int64                  `protobuf:"varint,3,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	Error         *types.Error           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_document_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{17}
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalMatches() int64 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *SearchResponse) GetError() *types.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ContentJson   string                 `protobuf:"bytes,2,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Highlights    map[string]string      `protobuf:"bytes,4,rep,name=highlights,proto3" json:"highlights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_document_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{18}
}

func (x *SearchResult) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SearchResult) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetHighlights() map[string]string {
	if x != nil {
		return x.Highlights
	}
	return nil
}

var File_document_proto protoreflect.FileDescriptor

const file_document_proto_rawDesc = "" +
	"\n" +
	"\x0edocument.proto\x12\fvaryd.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vtypes.proto\"\xdb\x01\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\rif_not_exists\x18\x02 \x01(\bR\vifNotExists\x12L\n" +
	"\aoptions\x18\x03 \x03(\v22.varyd.api.v1.CreateCollectionRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x18CreateCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\xd0\x01\n" +
	"\x15DropCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tif_exists\x18\x02 \x01(\bR\bifExists\x12J\n" +
	"\aoptions\x18\x03 \x03(\v20.varyd.api.v1.DropCollectionRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x16DropCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\xbb\x01\n" +
	"\x19DescribeCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12N\n" +
	"\aoptions\x18\x02 \x03(\v24.varyd.api.v1.DescribeCollectionRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x1aDescribeCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0edocument_count\x18\x03 \x01(\x03R\rdocumentCount\x12(\n" +
	"\x10index_term_count\x18\x04 \x01(\x03R\x0eindexTermCount\x12)\n" +
	"\x05error\x18\x05 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\xa1\x01\n" +
	"\x16ListCollectionsRequest\x12K\n" +
	"\aoptions\x18\x01 \x03(\v21.varyd.api.v1.ListCollectionsRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x17ListCollectionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\x83\x02\n" +
	"\x15InsertDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12!\n" +
	"\fcontent_json\x18\x03 \x01(\tR\vcontentJson\x12J\n" +
	"\aoptions\x18\x04 \x03(\v20.varyd.api.v1.InsertDocumentRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x16InsertDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\xda\x01\n" +
	"\x12GetDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12G\n" +
	"\aoptions\x18\x03 \x03(\v2-.varyd.api.v1.GetDocumentRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x13GetDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12!\n" +
	"\fcontent_json\x18\x03 \x01(\tR\vcontentJson\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x05error\x18\x05 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\x83\x02\n" +
	"\x15UpdateDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12!\n" +
	"\fcontent_json\x18\x03 \x01(\tR\vcontentJson\x12J\n" +
	"\aoptions\x18\x04 \x03(\v20.varyd.api.v1.UpdateDocumentRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x16UpdateDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x05error\x18\x03 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\xe0\x01\n" +
	"\x15DeleteDocumentRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12J\n" +
	"\aoptions\x18\x03 \x03(\v20.varyd.api.v1.DeleteDocumentRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x16DeleteDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\xa0\x03\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12<\n" +
	"\x05boost\x18\x04 \x03(\v2&.varyd.api.v1.SearchRequest.BoostEntryR\x05boost\x12\x1b\n" +
	"\tmin_score\x18\x05 \x01(\x02R\bminScore\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\x12B\n" +
	"\aoptions\x18\b \x03(\v2(.varyd.api.v1.SearchRequest.OptionsEntryR\aoptions\x1a8\n" +
	"\n" +
	"BoostEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\aresults\x18\x02 \x03(\v2\x1a.varyd.api.v1.SearchResultR\aresults\x12#\n" +
	"\rtotal_matches\x18\x03 \x01(\x03R\ftotalMatches\x12)\n" +
	"\x05error\x18\x04 \x01(\v2\x13.varyd.api.v1.ErrorR\x05error\"\xf3\x01\n" +
	"\fSearchResult\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12!\n" +
	"\fcontent_json\x18\x02 \x01(\tR\vcontentJson\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12J\n" +
	"\n" +
	"highlights\x18\x04 \x03(\v2*.varyd.api.v1.SearchResult.HighlightsEntryR\n" +
	"highlights\x1a=\n" +
	"\x0fHighlightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xca\x06\n" +
	"\x0fDocumentService\x12a\n" +
	"\x10CreateCollection\x12%.varyd.api.v1.CreateCollectionRequest\x1a&.varyd.api.v1.CreateCollectionResponse\x12[\n" +
	"\x0eDropCollection\x12#.varyd.api.v1.DropCollectionRequest\x1a$.varyd.api.v1.DropCollectionResponse\x12g\n" +
	"\x12DescribeCollection\x12'.varyd.api.v1.DescribeCollectionRequest\x1a(.varyd.api.v1.DescribeCollectionResponse\x12^\n" +
	"\x0fListCollections\x12$.varyd.api.v1.ListCollectionsRequest\x1a%.varyd.api.v1.ListCollectionsResponse\x12[\n" +
	"\x0eInsertDocument\x12#.varyd.api.v1.InsertDocumentRequest\x1a$.varyd.api.v1.InsertDocumentResponse\x12R\n" +
	"\vGetDocument\x12 .varyd.api.v1.GetDocumentRequest\x1a!.varyd.api.v1.GetDocumentResponse\x12[\n" +
	"\x0eUpdateDocument\x12#.varyd.api.v1.UpdateDocumentRequest\x1a$.varyd.api.v1.UpdateDocumentResponse\x12[\n" +
	"\x0eDeleteDocument\x12#.varyd.api.v1.DeleteDocumentRequest\x1a$.varyd.api.v1.DeleteDocumentResponse\x12C\n" +
	"\x06Search\x12\x1b.varyd.api.v1.SearchRequest\x1a\x1c.varyd.api.v1.SearchResponseB0Z.github.com/sqlrest/go-varyd/src/proto/documentb\x06proto3"

var (
	file_document_proto_rawDescOnce sync.Once
	file_document_proto_rawDescData []byte
)

func file_document_proto_rawDescGZIP() []byte {
	file_document_proto_rawDescOnce.Do(func() {
		file_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)))
	})
	return file_document_proto_rawDescData
}

var file_document_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_document_proto_goTypes = []any{
	(*CreateCollectionRequest)(nil),    // 0: varyd.api.v1.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),   // 1: varyd.api.v1.CreateCollectionResponse
	(*DropCollectionRequest)(nil),      // 2: varyd.api.v1.DropCollectionRequest
	(*DropCollectionResponse)(nil),     // 3: varyd.api.v1.DropCollectionResponse
	(*DescribeCollectionRequest)(nil),  // 4: varyd.api.v1.DescribeCollectionRequest
	(*DescribeCollectionResponse)(nil), // 5: varyd.api.v1.DescribeCollectionResponse
	(*ListCollectionsRequest)(nil),     // 6: varyd.api.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),    // 7: varyd.api.v1.ListCollectionsResponse
	(*InsertDocumentRequest)(nil),      // 8: varyd.api.v1.InsertDocumentRequest
	(*InsertDocumentResponse)(nil),     // 9: varyd.api.v1.InsertDocumentResponse
	(*GetDocumentRequest)(nil),         // 10: varyd.api.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),        // 11: varyd.api.v1.GetDocumentResponse
	(*UpdateDocumentRequest)(nil),      // 12: varyd.api.v1.UpdateDocumentRequest
	(*UpdateDocumentResponse)(nil),     // 13: varyd.api.v1.UpdateDocumentResponse
	(*DeleteDocumentRequest)(nil),      // 14: varyd.api.v1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),     // 15: varyd.api.v1.DeleteDocumentResponse
	(*SearchRequest)(nil),              // 16: varyd.api.v1.SearchRequest
	(*SearchResponse)(nil),             // 17: varyd.api.v1.SearchResponse
	(*SearchResult)(nil),               // 18: varyd.api.v1.SearchResult
	nil,                                // 19: varyd.api.v1.CreateCollectionRequest.OptionsEntry
	nil,                                // 20: varyd.api.v1.DropCollectionRequest.OptionsEntry
	nil,                                // 21: varyd.api.v1.DescribeCollectionRequest.OptionsEntry
	nil,                                // 22: varyd.api.v1.ListCollectionsRequest.OptionsEntry
	nil,                                // 23: varyd.api.v1.InsertDocumentRequest.OptionsEntry
	nil,                                // 24: varyd.api.v1.GetDocumentRequest.OptionsEntry
	nil,                                // 25: varyd.api.v1.UpdateDocumentRequest.OptionsEntry
	nil,                                // 26: varyd.api.v1.DeleteDocumentRequest.OptionsEntry
	nil,                                // 27: varyd.api.v1.SearchRequest.BoostEntry
	nil,                                // 28: varyd.api.v1.SearchRequest.OptionsEntry
	nil,                                // 29: varyd.api.v1.SearchResult.HighlightsEntry
	(*types.Error)(nil),                // 30: varyd.api.v1.Error
	(*timestamppb.Timestamp)(nil),      // 31: google.protobuf.Timestamp
}
var file_document_proto_depIdxs = []int32{
	19, // 0: varyd.api.v1.CreateCollectionRequest.options:type_name -> varyd.api.v1.CreateCollectionRequest.OptionsEntry
	30, // 1: varyd.api.v1.CreateCollectionResponse.error:type_name -> varyd.api.v1.Error
	20, // 2: varyd.api.v1.DropCollectionRequest.options:type_name -> varyd.api.v1.DropCollectionRequest.OptionsEntry
	30, // 3: varyd.api.v1.DropCollectionResponse.error:type_name -> varyd.api.v1.Error
	21, // 4: varyd.api.v1.DescribeCollectionRequest.options:type_name -> varyd.api.v1.DescribeCollectionRequest.OptionsEntry
	30, // 5: varyd.api.v1.DescribeCollectionResponse.error:type_name -> varyd.api.v1.Error
	22, // 6: varyd.api.v1.ListCollectionsRequest.options:type_name -> varyd.api.v1.ListCollectionsRequest.OptionsEntry
	30, // 7: varyd.api.v1.ListCollectionsResponse.error:type_name -> varyd.api.v1.Error
	23, // 8: varyd.api.v1.InsertDocumentRequest.options:type_name -> varyd.api.v1.InsertDocumentRequest.OptionsEntry
	30, // 9: varyd.api.v1.InsertDocumentResponse.error:type_name -> varyd.api.v1.Error
	24, // 10: varyd.api.v1.GetDocumentRequest.options:type_name -> varyd.api.v1.GetDocumentRequest.OptionsEntry
	31, // 11: varyd.api.v1.GetDocumentResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 12: varyd.api.v1.GetDocumentResponse.error:type_name -> varyd.api.v1.Error
	25, // 13: varyd.api.v1.UpdateDocumentRequest.options:type_name -> varyd.api.v1.UpdateDocumentRequest.OptionsEntry
	30, // 14: varyd.api.v1.UpdateDocumentResponse.error:type_name -> varyd.api.v1.Error
	26, // 15: varyd.api.v1.DeleteDocumentRequest.options:type_name -> varyd.api.v1.DeleteDocumentRequest.OptionsEntry
	30, // 16: varyd.api.v1.DeleteDocumentResponse.error:type_name -> varyd.api.v1.Error
	27, // 17: varyd.api.v1.SearchRequest.boost:type_name -> varyd.api.v1.SearchRequest.BoostEntry
	28, // 18: varyd.api.v1.SearchRequest.options:type_name -> varyd.api.v1.SearchRequest.OptionsEntry
	18, // 19: varyd.api.v1.SearchResponse.results:type_name -> varyd.api.v1.SearchResult
	30, // 20: varyd.api.v1.SearchResponse.error:type_name -> varyd.api.v1.Error
	29, // 21: varyd.api.v1.SearchResult.highlights:type_name -> varyd.api.v1.SearchResult.HighlightsEntry
	0,  // 22: varyd.api.v1.DocumentService.CreateCollection:input_type -> varyd.api.v1.CreateCollectionRequest
	2,  // 23: varyd.api.v1.DocumentService.DropCollection:input_type -> varyd.api.v1.DropCollectionRequest
	4,  // 24: varyd.api.v1.DocumentService.DescribeCollection:input_type -> varyd.api.v1.DescribeCollectionRequest
	6,  // 25: varyd.api.v1.DocumentService.ListCollections:input_type -> varyd.api.v1.ListCollectionsRequest
	8,  // 26: varyd.api.v1.DocumentService.InsertDocument:input_type -> varyd.api.v1.InsertDocumentRequest
	10, // 27: varyd.api.v1.DocumentService.GetDocument:input_type -> varyd.api.v1.GetDocumentRequest
	12, // 28: varyd.api.v1.DocumentService.UpdateDocument:input_type -> varyd.api.v1.UpdateDocumentRequest
	14, // 29: varyd.api.v1.DocumentService.DeleteDocument:input_type -> varyd.api.v1.DeleteDocumentRequest
	16, // 30: varyd.api.v1.DocumentService.Search:input_type -> varyd.api.v1.SearchRequest
	1,  // 31: varyd.api.v1.DocumentService.CreateCollection:output_type -> varyd.api.v1.CreateCollectionResponse
	3,  // 32: varyd.api.v1.DocumentService.DropCollection:output_type -> varyd.api.v1.DropCollectionResponse
	5,  // 33: varyd.api.v1.DocumentService.DescribeCollection:output_type -> varyd.api.v1.DescribeCollectionResponse
	7,  // 34: varyd.api.v1.DocumentService.ListCollections:output_type -> varyd.api.v1.ListCollectionsResponse
	9,  // 35: varyd.api.v1.DocumentService.InsertDocument:output_type -> varyd.api.v1.InsertDocumentResponse
	11, // 36: varyd.api.v1.DocumentService.GetDocument:output_type -> varyd.api.v1.GetDocumentResponse
	13, // 37: varyd.api.v1.DocumentService.UpdateDocument:output_type -> varyd.api.v1.UpdateDocumentResponse
	15, // 38: varyd.api.v1.DocumentService.DeleteDocument:output_type -> varyd.api.v1.DeleteDocumentResponse
	17, // 39: varyd.api.v1.DocumentService.Search:output_type -> varyd.api.v1.SearchResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_document_proto_init() }
func file_document_proto_init() {
	if File_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_proto_goTypes,
		DependencyIndexes: file_document_proto_depIdxs,
		MessageInfos:      file_document_proto_msgTypes,
	}.Build()
	File_document_proto = out.File
	file_document_proto_goTypes = nil
	file_document_proto_depIdxs = nil
}
