// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vector.proto

package vector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectorService_CreateVector_FullMethodName        = "/varyd.api.v1.VectorService/CreateVector"
	VectorService_GetVector_FullMethodName           = "/varyd.api.v1.VectorService/GetVector"
	VectorService_UpdateVector_FullMethodName        = "/varyd.api.v1.VectorService/UpdateVector"
	VectorService_DeleteVector_FullMethodName        = "/varyd.api.v1.VectorService/DeleteVector"
	VectorService_ListVectors_FullMethodName         = "/varyd.api.v1.VectorService/ListVectors"
	VectorService_SimilaritySearch_FullMethodName    = "/varyd.api.v1.VectorService/SimilaritySearch"
	VectorService_NearestNeighbors_FullMethodName    = "/varyd.api.v1.VectorService/NearestNeighbors"
	VectorService_VectorDistance_FullMethodName      = "/varyd.api.v1.VectorService/VectorDistance"
	VectorService_VectorAdd_FullMethodName           = "/varyd.api.v1.VectorService/VectorAdd"
	VectorService_VectorSubtract_FullMethodName      = "/varyd.api.v1.VectorService/VectorSubtract"
	VectorService_VectorMultiply_FullMethodName      = "/varyd.api.v1.VectorService/VectorMultiply"
	VectorService_VectorNormalize_FullMethodName     = "/varyd.api.v1.VectorService/VectorNormalize"
	VectorService_DotProduct_FullMethodName          = "/varyd.api.v1.VectorService/DotProduct"
	VectorService_GenerateEmbedding_FullMethodName   = "/varyd.api.v1.VectorService/GenerateEmbedding"
	VectorService_BatchEmbedding_FullMethodName      = "/varyd.api.v1.VectorService/BatchEmbedding"
	VectorService_EmbeddingSimilarity_FullMethodName = "/varyd.api.v1.VectorService/EmbeddingSimilarity"
	VectorService_VectorClustering_FullMethodName    = "/varyd.api.v1.VectorService/VectorClustering"
	VectorService_ClusterAnalysis_FullMethodName     = "/varyd.api.v1.VectorService/ClusterAnalysis"
	VectorService_CreateIndex_FullMethodName         = "/varyd.api.v1.VectorService/CreateIndex"
	VectorService_DeleteIndex_FullMethodName         = "/varyd.api.v1.VectorService/DeleteIndex"
	VectorService_ListIndexes_FullMethodName         = "/varyd.api.v1.VectorService/ListIndexes"
)

// VectorServiceClient is the client API for VectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorServiceClient interface {
	// Vector operations
	CreateVector(ctx context.Context, in *CreateVectorRequest, opts ...grpc.CallOption) (*CreateVectorResponse, error)
	GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error)
	UpdateVector(ctx context.Context, in *UpdateVectorRequest, opts ...grpc.CallOption) (*UpdateVectorResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
	ListVectors(ctx context.Context, in *ListVectorsRequest, opts ...grpc.CallOption) (*ListVectorsResponse, error)
	// Similarity operations
	SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SimilaritySearchResponse, error)
	NearestNeighbors(ctx context.Context, in *NearestNeighborsRequest, opts ...grpc.CallOption) (*NearestNeighborsResponse, error)
	VectorDistance(ctx context.Context, in *VectorDistanceRequest, opts ...grpc.CallOption) (*VectorDistanceResponse, error)
	// Vector operations
	VectorAdd(ctx context.Context, in *VectorAddRequest, opts ...grpc.CallOption) (*VectorAddResponse, error)
	VectorSubtract(ctx context.Context, in *VectorSubtractRequest, opts ...grpc.CallOption) (*VectorSubtractResponse, error)
	VectorMultiply(ctx context.Context, in *VectorMultiplyRequest, opts ...grpc.CallOption) (*VectorMultiplyResponse, error)
	VectorNormalize(ctx context.Context, in *VectorNormalizeRequest, opts ...grpc.CallOption) (*VectorNormalizeResponse, error)
	DotProduct(ctx context.Context, in *DotProductRequest, opts ...grpc.CallOption) (*DotProductResponse, error)
	// Embedding operations
	GenerateEmbedding(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error)
	BatchEmbedding(ctx context.Context, in *BatchEmbeddingRequest, opts ...grpc.CallOption) (*BatchEmbeddingResponse, error)
	EmbeddingSimilarity(ctx context.Context, in *EmbeddingSimilarityRequest, opts ...grpc.CallOption) (*EmbeddingSimilarityResponse, error)
	// Clustering operations
	VectorClustering(ctx context.Context, in *VectorClusteringRequest, opts ...grpc.CallOption) (*VectorClusteringResponse, error)
	ClusterAnalysis(ctx context.Context, in *ClusterAnalysisRequest, opts ...grpc.CallOption) (*ClusterAnalysisResponse, error)
	// Index operations
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error)
}

type vectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorServiceClient(cc grpc.ClientConnInterface) VectorServiceClient {
	return &vectorServiceClient{cc}
}

func (c *vectorServiceClient) CreateVector(ctx context.Context, in *CreateVectorRequest, opts ...grpc.CallOption) (*CreateVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_CreateVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_GetVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) UpdateVector(ctx context.Context, in *UpdateVectorRequest, opts ...grpc.CallOption) (*UpdateVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_UpdateVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, VectorService_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ListVectors(ctx context.Context, in *ListVectorsRequest, opts ...grpc.CallOption) (*ListVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVectorsResponse)
	err := c.cc.Invoke(ctx, VectorService_ListVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SimilaritySearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimilaritySearchResponse)
	err := c.cc.Invoke(ctx, VectorService_SimilaritySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) NearestNeighbors(ctx context.Context, in *NearestNeighborsRequest, opts ...grpc.CallOption) (*NearestNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NearestNeighborsResponse)
	err := c.cc.Invoke(ctx, VectorService_NearestNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) VectorDistance(ctx context.Context, in *VectorDistanceRequest, opts ...grpc.CallOption) (*VectorDistanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorDistanceResponse)
	err := c.cc.Invoke(ctx, VectorService_VectorDistance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) VectorAdd(ctx context.Context, in *VectorAddRequest, opts ...grpc.CallOption) (*VectorAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorAddResponse)
	err := c.cc.Invoke(ctx, VectorService_VectorAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) VectorSubtract(ctx context.Context, in *VectorSubtractRequest, opts ...grpc.CallOption) (*VectorSubtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSubtractResponse)
	err := c.cc.Invoke(ctx, VectorService_VectorSubtract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) VectorMultiply(ctx context.Context, in *VectorMultiplyRequest, opts ...grpc.CallOption) (*VectorMultiplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorMultiplyResponse)
	err := c.cc.Invoke(ctx, VectorService_VectorMultiply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) VectorNormalize(ctx context.Context, in *VectorNormalizeRequest, opts ...grpc.CallOption) (*VectorNormalizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorNormalizeResponse)
	err := c.cc.Invoke(ctx, VectorService_VectorNormalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) DotProduct(ctx context.Context, in *DotProductRequest, opts ...grpc.CallOption) (*DotProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DotProductResponse)
	err := c.cc.Invoke(ctx, VectorService_DotProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) GenerateEmbedding(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateEmbeddingResponse)
	err := c.cc.Invoke(ctx, VectorService_GenerateEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) BatchEmbedding(ctx context.Context, in *BatchEmbeddingRequest, opts ...grpc.CallOption) (*BatchEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEmbeddingResponse)
	err := c.cc.Invoke(ctx, VectorService_BatchEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) EmbeddingSimilarity(ctx context.Context, in *EmbeddingSimilarityRequest, opts ...grpc.CallOption) (*EmbeddingSimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingSimilarityResponse)
	err := c.cc.Invoke(ctx, VectorService_EmbeddingSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) VectorClustering(ctx context.Context, in *VectorClusteringRequest, opts ...grpc.CallOption) (*VectorClusteringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorClusteringResponse)
	err := c.cc.Invoke(ctx, VectorService_VectorClustering_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ClusterAnalysis(ctx context.Context, in *ClusterAnalysisRequest, opts ...grpc.CallOption) (*ClusterAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterAnalysisResponse)
	err := c.cc.Invoke(ctx, VectorService_ClusterAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, VectorService_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, VectorService_DeleteIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorServiceClient) ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndexesResponse)
	err := c.cc.Invoke(ctx, VectorService_ListIndexes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServiceServer is the server API for VectorService service.
// All implementations must embed UnimplementedVectorServiceServer
// for forward compatibility.
type VectorServiceServer interface {
	// Vector operations
	CreateVector(context.Context, *CreateVectorRequest) (*CreateVectorResponse, error)
	GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error)
	UpdateVector(context.Context, *UpdateVectorRequest) (*UpdateVectorResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	ListVectors(context.Context, *ListVectorsRequest) (*ListVectorsResponse, error)
	// Similarity operations
	SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SimilaritySearchResponse, error)
	NearestNeighbors(context.Context, *NearestNeighborsRequest) (*NearestNeighborsResponse, error)
	VectorDistance(context.Context, *VectorDistanceRequest) (*VectorDistanceResponse, error)
	// Vector operations
	VectorAdd(context.Context, *VectorAddRequest) (*VectorAddResponse, error)
	VectorSubtract(context.Context, *VectorSubtractRequest) (*VectorSubtractResponse, error)
	VectorMultiply(context.Context, *VectorMultiplyRequest) (*VectorMultiplyResponse, error)
	VectorNormalize(context.Context, *VectorNormalizeRequest) (*VectorNormalizeResponse, error)
	DotProduct(context.Context, *DotProductRequest) (*DotProductResponse, error)
	// Embedding operations
	GenerateEmbedding(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error)
	BatchEmbedding(context.Context, *BatchEmbeddingRequest) (*BatchEmbeddingResponse, error)
	EmbeddingSimilarity(context.Context, *EmbeddingSimilarityRequest) (*EmbeddingSimilarityResponse, error)
	// Clustering operations
	VectorClustering(context.Context, *VectorClusteringRequest) (*VectorClusteringResponse, error)
	ClusterAnalysis(context.Context, *ClusterAnalysisRequest) (*ClusterAnalysisResponse, error)
	// Index operations
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error)
	mustEmbedUnimplementedVectorServiceServer()
}

// UnimplementedVectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorServiceServer struct{}

func (UnimplementedVectorServiceServer) CreateVector(context.Context, *CreateVectorRequest) (*CreateVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVector not implemented")
}
func (UnimplementedVectorServiceServer) GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVector not implemented")
}
func (UnimplementedVectorServiceServer) UpdateVector(context.Context, *UpdateVectorRequest) (*UpdateVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVector not implemented")
}
func (UnimplementedVectorServiceServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedVectorServiceServer) ListVectors(context.Context, *ListVectorsRequest) (*ListVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVectors not implemented")
}
func (UnimplementedVectorServiceServer) SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SimilaritySearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimilaritySearch not implemented")
}
func (UnimplementedVectorServiceServer) NearestNeighbors(context.Context, *NearestNeighborsRequest) (*NearestNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NearestNeighbors not implemented")
}
func (UnimplementedVectorServiceServer) VectorDistance(context.Context, *VectorDistanceRequest) (*VectorDistanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorDistance not implemented")
}
func (UnimplementedVectorServiceServer) VectorAdd(context.Context, *VectorAddRequest) (*VectorAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorAdd not implemented")
}
func (UnimplementedVectorServiceServer) VectorSubtract(context.Context, *VectorSubtractRequest) (*VectorSubtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSubtract not implemented")
}
func (UnimplementedVectorServiceServer) VectorMultiply(context.Context, *VectorMultiplyRequest) (*VectorMultiplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorMultiply not implemented")
}
func (UnimplementedVectorServiceServer) VectorNormalize(context.Context, *VectorNormalizeRequest) (*VectorNormalizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorNormalize not implemented")
}
func (UnimplementedVectorServiceServer) DotProduct(context.Context, *DotProductRequest) (*DotProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DotProduct not implemented")
}
func (UnimplementedVectorServiceServer) GenerateEmbedding(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateEmbedding not implemented")
}
func (UnimplementedVectorServiceServer) BatchEmbedding(context.Context, *BatchEmbeddingRequest) (*BatchEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchEmbedding not implemented")
}
func (UnimplementedVectorServiceServer) EmbeddingSimilarity(context.Context, *EmbeddingSimilarityRequest) (*EmbeddingSimilarityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbeddingSimilarity not implemented")
}
func (UnimplementedVectorServiceServer) VectorClustering(context.Context, *VectorClusteringRequest) (*VectorClusteringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorClustering not implemented")
}
func (UnimplementedVectorServiceServer) ClusterAnalysis(context.Context, *ClusterAnalysisRequest) (*ClusterAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterAnalysis not implemented")
}
func (UnimplementedVectorServiceServer) CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedVectorServiceServer) DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (UnimplementedVectorServiceServer) ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIndexes not implemented")
}
func (UnimplementedVectorServiceServer) mustEmbedUnimplementedVectorServiceServer() {}
func (UnimplementedVectorServiceServer) testEmbeddedByValue()                       {}

// UnsafeVectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServiceServer will
// result in compilation errors.
type UnsafeVectorServiceServer interface {
	mustEmbedUnimplementedVectorServiceServer()
}

func RegisterVectorServiceServer(s grpc.ServiceRegistrar, srv VectorServiceServer) {
	// If the following call panics, it indicates UnimplementedVectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorService_ServiceDesc, srv)
}

func _VectorService_CreateVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).CreateVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_CreateVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).CreateVector(ctx, req.(*CreateVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_GetVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).GetVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_GetVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).GetVector(ctx, req.(*GetVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_UpdateVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).UpdateVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_UpdateVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).UpdateVector(ctx, req.(*UpdateVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ListVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ListVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ListVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ListVectors(ctx, req.(*ListVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_SimilaritySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilaritySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).SimilaritySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_SimilaritySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).SimilaritySearch(ctx, req.(*SimilaritySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_NearestNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearestNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).NearestNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_NearestNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).NearestNeighbors(ctx, req.(*NearestNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_VectorDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).VectorDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_VectorDistance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).VectorDistance(ctx, req.(*VectorDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_VectorAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).VectorAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_VectorAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).VectorAdd(ctx, req.(*VectorAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_VectorSubtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSubtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).VectorSubtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_VectorSubtract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).VectorSubtract(ctx, req.(*VectorSubtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_VectorMultiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorMultiplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).VectorMultiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_VectorMultiply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).VectorMultiply(ctx, req.(*VectorMultiplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_VectorNormalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorNormalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).VectorNormalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_VectorNormalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).VectorNormalize(ctx, req.(*VectorNormalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_DotProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DotProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).DotProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_DotProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).DotProduct(ctx, req.(*DotProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_GenerateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).GenerateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_GenerateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).GenerateEmbedding(ctx, req.(*GenerateEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_BatchEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).BatchEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_BatchEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).BatchEmbedding(ctx, req.(*BatchEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_EmbeddingSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingSimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).EmbeddingSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_EmbeddingSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).EmbeddingSimilarity(ctx, req.(*EmbeddingSimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_VectorClustering_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorClusteringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).VectorClustering(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_VectorClustering_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).VectorClustering(ctx, req.(*VectorClusteringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ClusterAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ClusterAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ClusterAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ClusterAnalysis(ctx, req.(*ClusterAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_DeleteIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorService_ListIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndexesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServiceServer).ListIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorService_ListIndexes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServiceServer).ListIndexes(ctx, req.(*ListIndexesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorService_ServiceDesc is the grpc.ServiceDesc for VectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "varyd.api.v1.VectorService",
	HandlerType: (*VectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVector",
			Handler:    _VectorService_CreateVector_Handler,
		},
		{
			MethodName: "GetVector",
			Handler:    _VectorService_GetVector_Handler,
		},
		{
			MethodName: "UpdateVector",
			Handler:    _VectorService_UpdateVector_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _VectorService_DeleteVector_Handler,
		},
		{
			MethodName: "ListVectors",
			Handler:    _VectorService_ListVectors_Handler,
		},
		{
			MethodName: "SimilaritySearch",
			Handler:    _VectorService_SimilaritySearch_Handler,
		},
		{
			MethodName: "NearestNeighbors",
			Handler:    _VectorService_NearestNeighbors_Handler,
		},
		{
			MethodName: "VectorDistance",
			Handler:    _VectorService_VectorDistance_Handler,
		},
		{
			MethodName: "VectorAdd",
			Handler:    _VectorService_VectorAdd_Handler,
		},
		{
			MethodName: "VectorSubtract",
			Handler:    _VectorService_VectorSubtract_Handler,
		},
		{
			MethodName: "VectorMultiply",
			Handler:    _VectorService_VectorMultiply_Handler,
		},
		{
			MethodName: "VectorNormalize",
			Handler:    _VectorService_VectorNormalize_Handler,
		},
		{
			MethodName: "DotProduct",
			Handler:    _VectorService_DotProduct_Handler,
		},
		{
			MethodName: "GenerateEmbedding",
			Handler:    _VectorService_GenerateEmbedding_Handler,
		},
		{
			MethodName: "BatchEmbedding",
			Handler:    _VectorService_BatchEmbedding_Handler,
		},
		{
			MethodName: "EmbeddingSimilarity",
			Handler:    _VectorService_EmbeddingSimilarity_Handler,
		},
		{
			MethodName: "VectorClustering",
			Handler:    _VectorService_VectorClustering_Handler,
		},
		{
			MethodName: "ClusterAnalysis",
			Handler:    _VectorService_ClusterAnalysis_Handler,
		},
		{
			MethodName: "CreateIndex",
			Handler:    _VectorService_CreateIndex_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _VectorService_DeleteIndex_Handler,
		},
		{
			MethodName: "ListIndexes",
			Handler:    _VectorService_ListIndexes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vector.proto",
}
